### ISSUE TITLE
dependencies from soniakeys repo were moved under github.com/soniakeys/meeus/v3/

### ISSUE THREAD

**Issue by ldanicel** [StefanSchroeder/Gocal#4]
> 
go get github.com/StefanSchroeder/gocal
>
package github.com/soniakeys/meeus/julian: cannot find package "github.com/soniakeys/meeus/julian" in any of:
	/usr/local/Cellar/go/1.9.4/libexec/src/github.com/soniakeys/meeus/julian (from $GOROOT)
	/Users/xxx/go/src/github.com/soniakeys/meeus/julian (from $GOPATH)
package github.com/soniakeys/meeus/moonphase: cannot find package "github.com/soniakeys/meeus/moonphase" in any of:
/usr/local/Cellar/go/1.9.4/libexec/src/github.com/soniakeys/meeus/moonphase (from $GOROOT)
/Users/xxx/go/src/github.com/soniakeys/meeus/moonphase (from $GOPATH)

**Comment by StefanSchroeder** [comment]
Thanks for the comment. I am going to fix it.

**Comment by StefanSchroeder** [comment]
Was fixed in 2019. Cannot remember how I did it, but it works now
