### ISSUE TITLE
this package can't be built on case sensitive filesystem

### ISSUE THREAD

**Issue by djadala** [StefanSchroeder/Gocal#5]
Hi,
can you please rename all Gocal to gocall, or change in readme from 
```go get github.com/StefanSchroeder/gocal``` to
```go get github.com/StefanSchroeder/Gocal``` ?
Thanks

**Comment by StefanSchroeder** [comment]
Sure.

**Comment by StefanSchroeder** [comment]
Fixed a long time ago.
